### ISSUE TITLE
Issue in flatlist in group

### ISSUE THREAD

**Issue by Bhaumik-Tandan** [get-amigo/Amigo#12]
<img width="314" alt="image" src="https://github.com/Bhaumik-Tandan/Split-cash/assets/62440699/e5e2e9fa-3b6b-4282-afa8-18336dc3d616">

In the group feed page there in issue of duplicate key as well as if you scroll too hard it will scroll infinitely

<img width="1354" alt="image" src="https://github.com/Bhaumik-Tandan/Split-cash/assets/62440699/7449cd15-3ba6-4684-9c27-2b9fba598b57">

**Comment by Avik-creator** [comment]
@Bhaumik-Tandan Asking is the OTP in the onboarding section not working?

**Comment by tirthajyoti-ghosh** [comment]
In dev mode you can put any 10 digits as phone number and any 6 digits as OTP.

This is mentioned in the README.

**Comment by Avik-creator** [comment]
Ok saw that now. thank you

**Comment by Avik-creator** [comment]
@tirthajyoti-ghosh I did everything as mentioned in the readme. I setup the .env with the development variables in the .eas.json, but still now couldn't go past the OTP screen. Is there anything I am missing?
