### ISSUE TITLE
Rupee Symbol not aligned with the amount in android

### ISSUE THREAD

**Issue by Bhaumik-Tandan** [get-amigo/Amigo#13]
<img width="359" alt="image" src="https://github.com/Bhaumik-Tandan/Split-cash/assets/62440699/f91f9bc6-6d3e-4ee8-b118-592c05ff3bc7">

The rupee symbol is not properly aligned with the amount

**Comment by Harshksaw** [comment]
Assign this to me , Ft Wellfound candidate
