### ISSUE TITLE
Category Slider in Transaction page in not smoth

### ISSUE THREAD

**Issue by Bhaumik-Tandan** [get-amigo/Amigo#27]
<img width="318" alt="Screenshot 2024-04-16 at 12 18 43 PM" src="https://github.com/Bhaumik-Tandan/Amigo/assets/62440699/03625e27-b6e8-4b40-8e6d-f2b8ba07a229">

The category selector here is not easy to slide left and right in mobile

**Comment by Satyam0327** [comment]
Can i work on this issue .

**Comment by Satyam0327** [comment]
Can you explain more about the issue.

**Comment by Bhaumik-Tandan** [comment]
> Can you explain more about the issue.

 When you navigate to the "Create Transaction" screen and attempt to slide the category slider to the right, it seems to be functioning with difficulty. It appears that the slider does not move smoothly.
