### ISSUE TITLE
contact list constantly changing while adding contacts to a group

### ISSUE THREAD

**Issue by Sumit0071** [get-amigo/Amigo#42]
https://github.com/get-amigo/Amigo/assets/109267742/33d4be19-5169-4327-9b42-508d2e96737f

**Comment by Harshksaw** [comment]
@Sumit0071 Please specify which device was it

**Comment by Harshksaw** [comment]
https://github.com/get-amigo/Amigo/assets/95240459/51fdb164-3a0c-4844-b8b6-498c47c01a00



Here it seems, Okay

https://github.com/get-amigo/Amigo/assets/95240459/0d0a7eae-e02a-4773-af64-71ea4f023752
